Repository NotYuSheng/OmniPDF, pull requests merged in 2025-06, with the labels that each got.

#35 refactor: move S3 utility functions to shared utils folder for reuse …
  docker-compose.yml
  pdf_processor_service/Dockerfile
  pdf_processor_service/routers/documents/upload.py
  shared_utils/__init__.py
  shared_utils/s3_utils.py
Labels: fix, refactor

#38 doc: added new sub issue template
  .github/ISSUE_TEMPLATE/sub-issue.md
Labels: documentation

#66 feat(ci): Add Trivy CVE scanning before image publish
  .github/workflows/trivy.yml
Labels: security, feature
